### ISSUE TITLE
C++ standard policy

### ISSUE THREAD

**Issue by dutkalex** [kokkos/kokkos-comm#44]
Hi there!
After a quick look at the code, it seems like the current implementation requires a C++20 compiler. I was wondering if this is a deliberate choice (to deviate from the general KokkosCore policy I mean) or just the result of the current experimental status of the project. As some GPU compilers do not support C++20, it would be nice to require only a C++17 compiler for now IMHO. 
Working on a daily basis with MPI and Kokkos for a few years now, I have developed similar wrappers for our new CFD solver and I'd be very happy to discuss and help develop this project!
Best regards,
Alex

**Comment by cwpearson** [comment]
Hi Alex!

Any contribution you'd like to make or thoughts you have would be very welcome. There is an `mpi-interop` channel in `kokkosteam.slack.com` if you would like to join us there as well.

Yes, C++20 is an intentional choice - we're basically expecting this will be production-ready around the same timeline that Kokkos starts to require C++20. I'll add this to the documentation.

At the moment, it is purely a happy accident if GPU-aware MPI works, however that is obviously a high priority for us.

**Comment by dutkalex** [comment]
Thanks for the quick answer. The argument makes sense. I will check the slack channel :)
