### ISSUE TITLE
[Question] Buffered mode

### ISSUE THREAD

**Issue by dutkalex** [kokkos/kokkos-comm#61]
Hi! I notice that the `CommMode` enum does not include the buffered mode. Is this intentional or just an oversight?
Best regards,
Alex

**Comment by dssgabriel** [comment]
This is intentional (see [related PR](https://github.com/kokkos/kokkos-comm/pull/30#issue-2237707823)), as the `Buffered` communication mode requires manual buffer attachment from the user through `MPI_Buffer_attach()`.
As our currently targeted applications do not need support for buffered communications, we just dismissed it.

We're currently thinking about adding functions for initializing, finalizing and, more generally, managing `KokkosComm`; this may change soon.

**Comment by devreal** [comment]
For the record: MPI 4.1 added `MPI_COMM_ATTACH_BUFFER` and `MPI_SESSION_ATTACH_BUFFER` to limit the scope of buffers to a communicator or session. It also added `MPI_BUFFER_AUTOMATIC` to enable automatic buffer allocation. Not sure what the implementation status is but this would be useful here once its provided.

**Comment by dssgabriel** [comment]
Indeed, especially if we want to go the `MPI_Session` route. I am going to look into it, thanks @devreal.

**Comment by dutkalex** [comment]
The argument makes sense. Thanks for the answer 🙃
(You can close the issue if you wish)
